version: '3.8'
#password123etretrerteert
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - '5433:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - db
      - gosearch
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'

  gosearch:
    build:
      context: ./gosearch
      dockerfile: Dockerfile
    environment:
      - PORT=8081
    ports:
      - '8081:8081'
    # Remove volume mount - it overwrites the compiled binary
    # volumes:
    #   - ./gosearch:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
